name: Fetch layout

on:
  workflow_dispatch:
    inputs:
      layout_geometry:
        description: "Keyboard type"
        type: choice
        options:
          - voyager
          - moonlander/reva
          - moonlander/revb
          - ergodox_ez
          - ergodox_ez/m32u4/glow
          - ergodox_ez/m32u4/shine
          - ergodox_ez/stm32
          - ergodox_ez/stm32/glow
          - ergodox_ez/stm32/shine
          - planck_ez
          - planck_ez/glow
        default: voyager
      layout_id:
        description: "Layout id available in URL https://configure.zsa.io/voyager/[layout_geometry]/[layout_id]/latest"
        required: true
        default: "Lm4R0"
  workflow_call:
    inputs:
      layout_geometry:
        type: string
        required: true
        default: voyager
      layout_id:
        type: string
        required: true

permissions:
  contents: write

jobs:
  fetch-layout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Fetch layout
        run: |
          ./scripts/fetch-layout.sh \
            "${{ inputs.layout_id || github.event.inputs.layout_id }}" \
            "${{ inputs.layout_geometry || github.event.inputs.layout_geometry }}"
      - name: Commit and push if changes
        env:
          CHANGE_DESCRIPTION: ${{ steps.download-layout-source.outputs.change_description }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          printf "✨(oryx): %s\n" "$CHANGE_DESCRIPTION" | git commit -F - || echo "No layout change"
          git push
